name: "AceStream Engine ARM"
description: "AceStream Engine para dispositivos ARM en Home Assistant"
version: "1.0.15"
slug: "acestream_engine_arm"
init: false
arch:
  - armv7
  - aarch64
ports:
  6878/tcp: 6878
  8621/tcp: 8621
  8000/tcp: 8000
  62062/tcp: 62062
options:
  ALLOW_REMOTE_ACCESS: "yes"
  PRODUCT_KEY: ""
  MAX_CONNECTIONS: "500"
schema:
  ALLOW_REMOTE_ACCESS: "str"
  PRODUCT_KEY: "str?"
  MAX_CONNECTIONS: "str"
