name: AceStream HA Addon ARM
slug: acestream_engine_addon
version: 3.2.7.6
description: Add-on para AceStream Engine en ARM
arch:
  - armv7
  - aarch64
startup: application
boot: auto
options:
  acestream_port: 6878
  shared_memory: /dev/shm
  vlc_mode: local
schema:
  acestream_port: int
  shared_memory: str
  vlc_mode: "list(local|docker)"
ports:
  "6878/tcp": 6878
webui: "http://[HOST]:[PORT:6878]"
image: futebas/acestream-engine-arm
