name: Acestream Engine
version: 1.0
slug: acestream_engine
description: Add-on para ejecutar Acestream Engine basado en futebas/acestream-engine-arm
url: https://github.com/asopaipa/acestream_ha_addon_arm
init: false
arch:
  - aarch64
  - armv7
  - armv8
options:
  ACE_CONFIG_OPTION: "- ALLOW_REMOTE_ACCESS=yes"
  ACE_PORT: '6878'
schema:
  ACE_CONFIG_OPTION: str
  ACE_PORT: int
ports:
  6878/tcp: "[ACE_PORT]"
ports_description:
  6878/tcp: Acestream port
