name: AceStream HA Addon ARM
slug: acestream_engine_addon
version: 3.2.7.6
description: Add-on para AceStream Engine en ARM
arch:
  - armv7
  - aarch64
startup: application
boot: auto
options:
  acestream_port: 6878
schema:
  acestream_port: int
ports:
  "6878/tcp": [acestream_port]
webui: "http://[HOST]:[PORT:6878]"
image: futebas/acestream-engine-arm
