name: AceStream HA Addon ARM
slug: acestream_engine_addon
version: 3.2.7.7
description: Add-on para AceStream Engine en ARM
arch:
  - armv7
  - aarch64
startup: application
boot: auto
options:
  ACE_CONFIG_OPTION: "- ALLOW_REMOTE_ACCESS=yes"
schema:
  ACE_CONFIG_OPTION: str
ports:
  "6878/tcp": 6878
image: futebas/acestream-engine-arm
