name: AceStream HA Addon ARM
slug: acestream_engine_addon
version: 3.2.7.6
description: Add-on para AceStream Engine en ARM
arch:
  - armv7
  - aarch64
startup: application
boot: auto
options:
  ACE_PORT: 6878
schema:
  ACE_PORT: int
ports:
  "6878/tcp": [ACE_PORT]
image: futebas/acestream-engine-arm
